### ISSUE TITLE
Missing catch of TypeError

### ISSUE THREAD

**Issue by nobbi1991** [spacemanspiff2007/eascheduler#24]
Please check https://github.com/spacemanspiff2007/eascheduler/blob/main/src/eascheduler/builder/helper.py#L105.

In my opinion a catch of `TypeError` is missing. Please also check if `ValueError` is correct.

To reproduce my bug, try to call get_instant with `datetime.time`.

If this bug is fixed, please also release a bugfix release for HABApp.

**Comment by spacemanspiff2007** [comment]
fixed in 0.2.2

**Comment by nobbi1991** [comment]
I think you forgot to trigger the 0.2.2 release ;)
-> no publish python run and the latest pypi version is 0.2.1

**Comment by spacemanspiff2007** [comment]
You are correct, somehow I forgot. I just did the release so it should be available

**Comment by nobbi1991** [comment]
No problem. Now, it is available. Thanks👍
